export const CARD_BG = [
  { id: 1, bgcolor: "#E6F4EA" }, // light green
  { id: 2, bgcolor: "#E8F0FE" }, // light blue
  { id: 3, bgcolor: "#FFF4E5" }, // light orange
  { id: 4, bgcolor: "#FCE8E6" }, // light red
  { id: 5, bgcolor: "#F3E8FF" }, // light purple
  { id: 6, bgcolor: "#E0F7FA" }, // teal
  { id: 7, bgcolor: "#FFFDE7" }, // yellow
  { id: 8, bgcolor: "#F1F8E9" }, // mint green
  { id: 9, bgcolor: "#EDE7F6" }, // lavender
  { id: 10, bgcolor: "#FFEBEE" }, // pink
];


export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: "03",
    title: "Beyond Just Answers",
    description:
      "Understand the 'why' behind each answer with detailed explanations generated by AI, helping you truly master each concept.",
  },
  {
    id: "04",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top, making your learning more organized.",
  },
  {
    id: "05",
    title: "Save, Organize, and Revisit",
    description:
      "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right where you left off.",
  },
];
