export const CARD_BG=[
  {id:1,bgcolor:'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)'},
  {id:2,bgcolor:'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)'},
  {id:3,bgcolor:'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)'},
  {id:4,bgcolor:'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)'},
  {id:5,bgcolor:'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)'},
  {id:6,bgcolor:'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)'},
  {id:7,bgcolor:'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)'},
  {id:8,bgcolor:'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)'},
  {id:9,bgcolor:'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)'},
  {id:10,bgcolor:'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)'},

];


export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: "03",
    title: "Beyond Just Answers",
    description:
      "Understand the 'why' behind each answer with detailed explanations generated by AI, helping you truly master each concept.",
  },
  {
    id: "04",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top, making your learning more organized.",
  },
  {
    id: "05",
    title: "Save, Organize, and Revisit",
    description:
      "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right where you left off.",
  },
];
